server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti-demo?autoReconnect=true&failOverReadOnly=false&characterEncoding=utf-8&useSSL=false
    username: root
    password: root